name: OSVersion

on: push

jobs:
  test:
    strategy:
      matrix:
        shell: [pwsh]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - shell: powershell
            os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run a multi-line script
        shell: pwsh
        run: |
          Write-Host '::group::OSVersion'
          Write-Verbose ([System.Environment]::OSVersion | Out-String) -Verbose
          Write-Host '::endgroup::'

          Write-Host '::group::PSVersionTable'
          Write-Verbose ($PSVersionTable | Out-String) -Verbose
          Write-Host '::endgroup::'

          Write-Host '::group::Environment variables'
          Write-Verbose (Get-ChildItem env: | sort-object Name | Select-Object Name, Value | Out-String) -Verbose
          Write-Host '::endgroup::'

          Write-Host '::group::PowerShell variables'
          Write-Verbose (Get-Variable | Format-Table -AutoSize | Out-String) -Verbose
          Write-Host '::endgroup::'
