name: OSVersion

on: push

jobs:
  test:
    strategy:
      matrix:
        shell: [pwsh]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - shell: powershell
            os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run a multi-line script
        shell: ${{ matrix.shell }}
        run: |
          Write-Host '::group::OSVersion'
          $OSVersion = [System.Environment]::OSVersion
          Write-Host '::endgroup::'

          Write-Host '::group::Environment variables'
          Get-ChildItem env: | sort-object Name | Select-Object Name, Value
          Write-Host '::endgroup::'

          Write-Host '::group::PowerShell variables'
          Get-Variable | Select-Object Name, Value
          Write-Host '::endgroup::'
