name: Publish

on:
  workflow_dispatch:
    inputs:
      WorkflowRunID:
        description: The ID of the workflow run where the artifact will be download from.
        required: true
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR info
      uses: PSModule/Download-CIArtifact@init
      with:
        WorkflowID: CI.yml
        WorkflowRunID: ${{ github.event.inputs.WorkflowRunID }}
        ArtifactName: docs
        GITHUB_TOKEN: ${{ github.token }}
