name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR info
      shell: pwsh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        $PR = gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$env:GITHUB_REPOSITORY/commits/$env:GITHUB_SHA/pulls" | ConvertFrom-Json
        $PR  | ConvertTo-Json -Depth 100

        $WorkflowRuns = gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$env:GITHUB_REPOSITORY/actions/workflows/CI.yml/runs?a=this+is+value+of+a&b=valueOfB" | ConvertFrom-Json
        $WorkflowRuns | ConvertTo-Json -Depth 100
        
    - name: Debug
      uses: PSModule/Debug@main
