name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR info
      uses: PSModule/Download-CIArtifact@init
      with:
        WorkflowID: CI.yml
        ArtifactName: docs
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Debug
      uses: PSModule/Debug@main
