name: test2

on: [push]

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        shell: [pwsh]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - shell: powershell
            os: windows-latest
    runs-on: ${{ matrix.os }}
    outputs:
      passsed: ${{ steps.step1.outputs.passed }}
    steps:
      - id: step1
        if: matrix.os == 'windows-latest'
        shell: ${{ matrix.shell }}
        run: Write-Host "passed=${{ matrix.os == 'windows-latest' }}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          passed: ${{needs.job1.outputs.passed}}
        run: echo "$passed"
