on: push

jobs:
  test:
    strategy:
      matrix:
        shell: [pwsh]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - shell: powershell
            os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run a multi-line script
        shell: pwsh
        run: |
          ([System.Environment]::OSVersion).Platform

          Get-ChildItem env:
