name: test2

on: [push]

jobs:
  job0:
    name: Test source code
    strategy:
      fail-fast: false
      matrix:
        shell: [pwsh]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - shell: powershell
            os: windows-latest
    runs-on: ${{ matrix.os }}
    outputs:
      passed: ${{ steps.test.outputs.passed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload test results
        id: test
        uses: ./.github/actions/test.yml
        with:
          shell: ${{ matrix.shell }}

  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          Write-Host "Output from passed is ${{ needs.matrix_job.outputs.passed }}"

